VCS = vcs
VCS_OPTS = -sverilog -full64 -debug_access+all
FILES = filelist.f
TOP = tb_axi
SIMV = simv
VERDI = verdi
VERDI_OPTS = -sv -f $(FILES) -ssf waves.fsdb -top $(TOP)
# signal.rc is a GUI waveform layout file generated by Verdi. Use -ss
# rather than -play so the rc file is interpreted correctly.
VERDI_RC = signal.rc

all: $(SIMV)

$(SIMV): $(FILES) Makefile
	$(VCS) $(VCS_OPTS) -f $(FILES) -top $(TOP) -o $(SIMV) -l compile.log

run: $(SIMV)
	./$(SIMV) -l sim.log

clean:
	rm -rf $(SIMV) csrc simv.daidir *.vpd *.log

verdi:
	$(VERDI) $(VERDI_OPTS) -ss $(VERDI_RC)
